#pragma once
#ifndef UI_H
#define UI_H
#ifdef __cplusplus
extern "C" {
#endif
typedef char (*currarr)[1024];

typedef struct UI_ UI_;

extern UI_ UI;



struct UI_
{
	/**
	* @brief			Inits the UI
	* @return			Returns 1 if the init was successfull, else 0.
	*/

	unsigned(*init)();
	/**
	* @brief 			Generate an event in the UI
	* @param ev			Event generated by the event generator
	* @return 			Returns 0 if the event was processed, returns ev if the event was not processed.
	*/
	char(*input)(char ev);
	
	char*(*getFile)();
	char*(*getPath)();
	void(*exitFile)();

	currarr  (*getCurrent)(unsigned* sz, unsigned *pos);
	void(*close)();
};
#ifdef __cplusplus
}
#endif

#endif // !UI_H